# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8443110cd42b621fe70e8ce08182c88def42aba145e1a9ff90432e0f8044d5e938c68f81a5f2a03c05c88f4f2b6ded60fee483a3aaca9c6816fd40897a91235a

test:
  secret_key_base: 8f24b3e87e39ae356e71a27ee9ffcb95361f95361cf32c2a112e4025b6b5402ac39db1b55103da096852d09dd098e666d54ae47556e8a6ad8eaac1c8a5ff7b67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
